### PR TITLE
Update locale.rb

### PR DESCRIPTION
**Pull request by jcsky**
fixed safari HTTP_ACCEPT_LANGUAGE lowercase error (ex: "zh-tw")
"zh-tw" is not available locale, so replace it to "zh-TW"

### CODE REVIEW

**Comment by mpalmer** [comment]
Does this change build on top of some others, such as #118?  I'm seeing a lot of test suite failures, due to calling `I18n` methods that don't exist in the minimum versions of our gems.  If your code needs features in newer versions of gems, you'll need to update the gemspec and `test/gemfiles/*` to reflect that.

**Comment by mpalmer** [comment]
I *think* this is the same problem as #138 addresses.  If not, an updated PR that passes the test suite will be needed.

**Comment by skyplor** [comment]
Hi, I'm seeing the same issue currently for iOS devices' safari and chrome. They are returning 'zh-tw' instead of the standard 'zh-TW'. The build #138 does not address this problem because if our default is 'en', then it won't translate correctly.

Since the standard is for the country or region variant to be in uppercasing, can we update to auto convert that part to uppercasing?

**Comment by mpalmer** [comment]
This issue has been closed for coming up on three years.  If you want to see this fixed, you'll want to put up a PR.

**Comment by skyplor** [comment]
Thanks. my bad. I saw there is already a PR that addresses it. thanks again :)

**Pull request closed without merging**
