### PR TITLE
Remove Rack::Runtime middleware

### PR DESCRIPTION
**Pull request by andrykonchin**
The `Rack::Runtime` middleware was removed.

## Notes

It duplicates a middleware with the same name in the `rack` gem (defined [here](https://github.com/rack/rack/blob/master/lib/rack/runtime.rb)).

`Rack::Runtime` was added to `rack-contrib` on Jul 2009 and was imported into `rack` on Dec 2009. Since then `rack-contrib` provides outdated version which shadowed the `rack`' one.

## Concerns

Looks line it's a breaking change and it should wait for the next major version release.

Maybe it's a good time to revise existing middlewares, review their APIs and remove deprecated ones (e.g. `PostBodyContentTypeParser`).

### CODE REVIEW

**Comment by mpalmer** [comment]
The first thought that comes to mind: is the core rack `Rack::Runtime` backwards-compatible with what we're shipping?  If so, we can rip out our version, keep the file (for `require` compatibility purposes), and have that make sure the core version is loaded.

If, on the other hand, the core variant has diverged incompatibly, we're stuck with it until v3.  I'm not averse to the idea of opening up a `3.x` branch and starting to put breaking changes in there, but there's a tiny part of me that thinks that, since we've managed to keep major version parity with `rack` so far, it'd be nice to try and stick to that if we can manage it, so it'd be a while until we actually put out `3.0.0` proper.  :grinning:

**Comment by ioquatix** [comment]
I confirmed that they are functionally equivalent.

**Comment by ioquatix** [comment]
Not only are they functionality equivalent, but you could also argue it's buggy to have the same class defined twice. I'm okay with adding a require through to the rack equivalent, but our policy on that in Rack is changing and currently we do have a autoload in place.

**Comment by mpalmer** [comment]
I'm only concerned that someone out there is going to have `require 'rack/contrib/runtime'` in their code, and just nuking the file will break that, leading to Confusion and Delay.

**Comment by ioquatix** [comment]
Yes, and we can fix that by adding a require for the rack implementation. Happy to merge a PR to that end.

**Comment by andrykonchin** [comment]
@ioquatix 

Created PR https://github.com/rack/rack-contrib/pull/171 with repairing `rack/contrib/runtime.rb` file

**Pull request merged**
