### PR TITLE
Make JSONP a noop when the status is 1xx, 204 or 304.

### LINKED ISSUE #8: Make JSONP a noop when the status is 1xx, 204 or 304
Fix here: http://github.com/aslakhellesoy/rack-contrib/commit/952cb23311c69fcad16e5dfade746a3884b22b9e

Discussion here: http://groups.google.com/group/rack-devel/browse_thread/thread/f3fc7b1b4c9a66c0

### PR DESCRIPTION
**Pull request by mpalmer**
This fixes #8, and is simply an update of the patch referenced in that issue.

### CODE REVIEW

**Comment by jjb** [comment]
Looks good, but `STATUS_WITH_NO_ENTITY_BODY` isn't defined anywhere? But then how did Travis pass...

**Comment by mpalmer** [comment]
`STATUS_WITH_NO_ENTITY_BODY` is defined in `Rack::Utils`.

**Comment by jjb** [comment]
:cool:

**Comment by jjb** [comment]
@mpalmer did you intend to close this without merging it?

**Pull request closed without merging**
