### PR TITLE
Allow Etag/Last-Modified headers in Rack::StaticCache

### PR DESCRIPTION
**Pull request by ericboehs**
Server side caching techniques shouldn't be disallowed.

See: https://github.com/rack/rack-contrib/commit/3f42d3afe7323d322567d77cd404fb5bd8d9f1eb#commitcomment-5084830

### CODE REVIEW

**Comment by mpalmer** [comment]
The rationale appears to be that if there's an ETag and/or Last-Modified header, the user agent will always re-check the resource with `If-Modified-Since` and/or `If-None-Match`, even during the caching period.  Like @ericboehs, I think this is wrong, wrong, wrongity wrong reasoning, but I'm going to double-triple-check the specs before I merge this.

**Comment by jjb** [comment]
@mpalmer Do you not feel that this type of behavior change should go into a major release?

**Comment by jjb** [comment]
Also, perhaps before putting work into this middleware, we should compare its features to the extremely popular https://github.com/rtomayko/rack-cache. Perhaps this middleware is redundant.

Interestingly, @rtomayko, the creator of rack-cache, is the one who merged 3f42d3afe7323d322567d77cd404fb5bd8d9f1eb in 2009. Would be interesting to hear from him if he feels there is some value in maintaining this middleware.

**Comment by mpalmer** [comment]
Based on the README, I'm pretty sure rack-cache is *doing* the caching, rather than modifying the headers returned by a response in order to enable a cache from operating.

As far as it being a breaking change, I'm inclined to treat the removal of these headers as a straight-up bug, rather than being a regular behaviour change.  I'm open to having my mind changed on that, but at present I can't see that anyone can be relying on this behaviour.

**Comment by jjb** [comment]
> I'm pretty sure rack-cache is *doing* the caching, rather than modifying the headers returned by a response in order to enable a cache from operating.

:facepalm: - I got that backwards.

:+1: on merging this

I've created #109 with some related thoughts.

**Comment by mpalmer** [comment]
Yep, as I suspected, [RFC7234 section 4.3](http://tools.ietf.org/html/rfc7234#section-4.3) says that:

> When a cache has one or more stored responses for a requested URI, but cannot serve any of them (e.g., because they are not fresh, or one cannot be selected; see Section 4.1), it can use the conditional request mechanism

So the rationale provided to remove the headers which would enable a validation request to be made is specious, and also violates [RFC7232 section 2.2.1](http://tools.ietf.org/html/rfc7232#section-2.2.1) which states:

> An origin server SHOULD send Last-Modified for any selected representation for which a last modification date can be reasonably and consistently determined

and [RFC7232 section 2.3.1](http://tools.ietf.org/html/rfc7232#section-2.3.1) which states:

> An origin server SHOULD send an ETag for any selected representation for which detection of changes can be reasonably and consistently determined

on the basis that if a downstream middleware (or the app itself) was able to generate an ETag and/or Last-Modified header, then it *was* able to be "reasonable and consistently determined", and hence not sending them is a violation.

As such, I will be merging this PR into the 1.3.0 release, absent a persuasive argument in opposition to my reasoning above.

**Comment by ericboehs** [comment]
The only thing I could think of to add is perhaps a test to ensure the functionality doesn't get reverted.

**Comment by jjb** [comment]
:+1:

**Comment by jjb** [comment]
> The only thing I could think of to add is perhaps a test to ensure the functionality doesn't get reverted.

more tests in general are good but shouldn't block reverting this IMO

**Comment by ericboehs** [comment]
Well if they don't get added now they probably won't ever. But I'm okay with merging without them.

**Comment by mpalmer** [comment]
I'm not in favour of adding tests that attempt to "prove a negative".  Tests that try to ensure that a piece of software can never be modified to do something stupid can never be comprehensive, and while I don't subscribe to the notion that "if you can't achieve perfection, you shouldn't do anything", my feeling in this case is that in this case, a test to say, "you shouldn't filter these specific headers" isn't worth it.  It would be as productive to create a test which asserted that we don't call `exit(0)`.

**Comment by ericboehs** [comment]
Makes sense. Should I rebase master in?

**Comment by mpalmer** [comment]
Yep, if you rebase I'll pull it straight in.

**Comment by ericboehs** [comment]
@mpalmer There we go. Took a second. Watching my 4 month old and she wasn't allowing me to rebase. :baby_bottle: :)

**Comment by mpalmer** [comment]
Done diddly-doodly.  Thanks, @ericboehs.

**Comment by ericboehs** [comment]
Glad I could help. Now to actually use it somewhere.

**Pull request merged**
