### PR TITLE
Allow post body content custom parsing

### PR DESCRIPTION
**Pull request by Kris-LIBIS**
I enhanced the Post Body Content parsing wit the option to supply your own custom block to parse the POSTed body with.

For example:

``` ruby
  use Rack::PostBodyContentTypeParser do |body|
    { payload: JSON.parse(body) }
  end
```

This would cause the request body to be loaded into params[:payload] instead of directly into params. There are several use cases why this may be interesting to do:
- Allow the users of your Rack API to supply any JSON data in the body, not just JSON Hashes.
- When combining query parameters with request body, prevent overriding query parameters with body content.

Especially the last part is an important use case for us. We have an API that collects log entries from different sources. Each log entry has a fixed set of parameters that are required and payload that each source can fill in according to its own needs. The fixed parameters are query parameters, the optional payload is request body.

Without this patch the users of the API should take care of always creating a Hash and attach their payload in a 'payload' key of that hash. If they forget, and submit their payload hash as-is the payload is discarded without anybody noticing.

Worse, if the payload hash contains keys that match any of the query parameters, the query parameter values get overwritten as Rack::Request merges both GET and POST hashes without any remorse, causing the entry to be lost in the database as some of the key values contain unexpected values.

### CODE REVIEW

**Comment by mpalmer** [comment]
I've got a few reservations about this PR (which also apply to #66):

* In theory, at least, this middleware isn't *just* for JSON parsing (although that's all it does at the moment, the name doesn't indicate that it is JSON-only); by making the block "JSON only", we're removing the ability to add new content-type parsing later.
* I believe the current hawtness in supporting multiple JSON parsers is `multi_json`; we should use that rather than allow a custom parsing block.
* The POST body not being an object at the top-level is a problem (a really *big* problem, because `Rack::Request` calls `#merge` on it, which is sure to end in disaster).  However, adding a block like this just to fix that seems like overkill.  An option to the middleware, specifying a param to assign the request body to (with an exception raised if none is specified and the request body doesn't parse into a hash) would be a more suitable approach, IMO.

**Comment by jjb** [comment]
I think the JSON parser was just what @Kris-LIBIS used as an example. @Kris-LIBIS is that right? Do you have a more complicated example for us to consider?

fwiw regarding multi_json: the purpose of multi_json is so that whatever happens to be in the JSON namespace in your runtime will be used, for the purpose of supporting a variety of solutions on a variety of platforms (I think that's a fair summary, correct me if I'm wrong). So, it's not useful for specifying a particular parser for a particular context. It's useful for having the same API to JSON whether running on jruby on windows or MRI on linux.

**Comment by mpalmer** [comment]
You can definitely specify to `multi_json` which parser backend to use.  I've had to do it to wrestle an RFC7159-supporting JSON parser into use.

**Comment by Kris-LIBIS** [comment]
Well, it is almost two years ago that I posted this. But yes, I believe the main purpose was to put the request body into a dedicated param. At the time, we had an API call that allowed a 3rd party application to submit any JSON data in the request body to be submitted as annotation data. When a top level json parameter shared its name with one of the URL parameters, it was havoc.

With regards to the implementation of it, I anticipated that others may want to perform some specific testing, enhancements or normalization on the request body prior to submitting it to the API code. We anticipated that data could require some pre-processing in the future to accomodate new applications and/or API features.

Of course, looking at this two years later I might have implemented it differently. Not sure though. But really the only thing I was trying to solve then was the issue with the params hash merging as that was hurting us big time.

@mpalmer: I may be misinterpreting your remarks, but I am not sharing your concerns in the first and second pioints. Using multi_json would be fine with me - we may even have used in our application - but it does not matter IMHO as the block is what you would supply to the PostBodyContainer. It is not part of the middleware itself, but is code that you inject into it. The block is JSON only as that is the only thing our application expects to get in the body. The content of the block is whatever is needed in your application context. The only constraints are that the input is a request body and the output of the block will be used as request body further down the lane.

**Comment by matthewd** [comment]
Maybe relevant: https://github.com/rails/rails/pull/10576

**Comment by mpalmer** [comment]
Also relevant: flori/json#220

**Comment by jjb** [comment]
@matthewd thanks! i was googling high and low for that fraking PR and couldn't find it :bow:

**Comment by mpalmer** [comment]
@Kris-LIBIS' comments make sense -- if we document this as "you can do your own, completely arbitrary, parsing of the POST body if you pass a block -- hacker emptor!", then I can see this as being useful.  Any takers?

**Comment by Kris-LIBIS** [comment]
@mpalmer Sorry, I did not realize this PR had merge conflicts. But I just checked in the proper merge and test fixes. If there are no further objections could you consider still merging this?

**Comment by mpalmer** [comment]
I'm not averse to it on principle; I'll need to re-review the whole thing to load the state back into my head, though.

**Pull request merged**
