### PR TITLE
Add a CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by mpalmer**
To clearly document how things work around here.

Fellow maintainers: I'm up for driving this monthly release cycle forward (although if anyone else wants to volunteer to be part of the cycle, please let me know!).  If you don't agree with something in here, please speak up, otherwise I'll land this in a week or so, and thus it shall become Official Doctrine of the People's Committee For Rack-Contrib Maintenance.

### CODE REVIEW

**Comment by jjb** [comment]
Thank you @mpalmer for taking this initiative. The document looks great. Some thoughts on the document:

* Should we invite one or more rack maintainers to give input? (are you a rack maintainer?)
* The minor version release schedule seems a bit ambitious, since right now there is no schedule and maintenance has been almost nonexistent. Maybe don't commit to a schedule at first and see how things go?
* one last very minor thing: I'm partial to file names being either contributing.md or Contributing.md. I see no reason to do all-caps.

I also think we should discuss and define what is the purpose of the project. I've made another issue for this, #104. Perhaps we should see that discussion through before finalizing the contribution guidelines.

**Comment by mpalmer** [comment]
Hi @jjb,

Thanks for the feedback.

* Both @raggi and @chneukirchen are watchers on this repo, so they should have gotten this PR and I'd like to think they'd make it known if they felt my suggestion was inappropriate.  (*Please* do, guys!)
* I deliberately set an aggressive release schedule, because I find that it's much more motivational to make bold public statements, which I then feel duty-bound to adhere to.  (grin)
* Github's docs suggest that the file name must be `CONTRIBUTING.md` in order to get the automated integration with issues, etc; a quick test tells me that it can be all-lowercase, so I'll change that.

I'll add my thoughts to #104, also.

**Comment by chneukirchen** [comment]
All fine by me.

**Comment by jjb** [comment]
@mpalmer re: release schedule, noted, but for the record *you* are the only one committing to this, not all the maintainers :) Also, do you have write access for the rubygem? Who else does? Is there a recipe for how to publish the gem? I see some Rake tasks for building it. Are these what have been used? Are there other steps in the process?

**Comment by mpalmer** [comment]
I don't have publish access to the gem (yet), but I'm planning on getting it.  Building and publishing a gem isn't a tricky process, and [I've got enough experience doing it](https://rubygems.org/profiles/mpalmer) to be reasonably confident that isn't going to be a blocker.

**Comment by raggi** [comment]
SGTM.

mpalmer: feel free to ping me anytime you need stuff, happy to help. I can't always respond instantly, but feel free to be persistent I'll do all I can!

**Comment by mpalmer** [comment]
Landed.

**Comment by jjb** [comment]
:+1:

**Pull request closed without merging**
