### PR TITLE
add Criteria for inclusion section to README

### PR DESCRIPTION
**Pull request by jjb**
See discussion in https://github.com/rack/rack-contrib/issues/104

### CODE REVIEW

**Comment by mpalmer** [comment]
This looks OK to me.  It might be worth referencing `CONTRIBUTING.md` to provide "further details on acceptance criteria" or some such.

**Comment by jjb** [comment]
@mpalmer done

**Comment by jjb** [comment]
If you are fine with it, I will merge.

**Comment by mpalmer** [comment]
I love it.  I'm 100% in favour of your merging this.

**Pull request merged**
