### PR TITLE
Rack::Locale use default_locale if none matches

### PR DESCRIPTION
**Pull request by irohiroki**
Address #135 . Currently an Undefined method raises if none of Accept-Language matches to I18n.available_locales.

### CODE REVIEW

**Comment by mpalmer** [comment]
Methinks you're relying on behaviour in `I18n` that was introduced in a version later than the minimum version we're currently depending on, because a whole bunch of Travis runs are failing (ignore the 1.9.3 run with the `!`; that's broken for other reasons I am yet to figure out).

**Comment by irohiroki** [comment]
@mpalmer Thank you for telling me what's wrong with my PR. I just fixed the issue and now it passes with minimum version gems. Could you review the commit, or should I look into the failure on Travis? (1.9.3 with `!`)

**Comment by mpalmer** [comment]
This is all looking good.  Thanks for making everything solid.

> should I look into the failure on Travis?

No, you can ignore that error on 1.9.3; it's a bug in Travis (or the version of rubygems they're using) that I haven't been bothered to chase down.  Given that Ruby 1.9 won't be supported in the nearish future (due to Rack 2.x requiring Ruby 2.2) it's not really worth anyone's time to fix.

**Comment by jmettraux** [comment]
@irohiroki Thank you very much!

**Pull request merged**
