### PR TITLE
Fix StaticCache middleware

### PR DESCRIPTION
**Pull request by andrykonchin**
Changes:
- send Date header in response
- use current time in UTC (instead of system time) to calculate Expires header
- removed caching of Expires header value - it'a an absolute time and should be calculated for each request

Closes https://github.com/rack/rack-contrib/issues/58

### CODE REVIEW

**Comment by mpalmer** [comment]
You've been on a real tear, @andrykonchin, and all your work is excellent.  If you're intending on continuing maintenance work on rack-contrib in the future, I'd be happy to grant you push rights on the repo.

**Comment by jjb** [comment]
Nice! out of scope for this card but made me think, would be nice to have some means by which to only call `Time.now` once per request so all references to it are consistent and to reduce cpu complexity.

**Comment by mpalmer** [comment]
Yes, that would be a good thing.

**Comment by andrykonchin** [comment]
> If you're intending on continuing maintenance work on rack-contrib in the future, I'd be happy to grant you push rights on the repo.

Yes, it would be great to join the maintainers team. Thank you.

**Comment by mpalmer** [comment]
Invite sent!  Welcome to the club!

**Pull request merged**
