### PR TITLE
Created LazyConditionalGet middleware

### PR DESCRIPTION
**Pull request by mig-hub**
Hello,

Please let me know if anything is not good enough.
I struggled a bit with tests since I never used minitest before and always test middlewares with rack/test.

You could tell that I did with methods what I normally do with `let` in `RSpec`.

The purpose of the middleware is to provide the most basic mechanism for dealing with conditional gets without having to build the resource each time.

Let me know if anything is unclear.

Cheers,
mig

### CODE REVIEW

**Comment by mpalmer** [comment]
Thanks for the PR.  It's certainly an interesting approach to the problem.

I've got quite a number of comments about the patch itself, which I'll make as commit comments.

**Comment by mig-hub** [comment]
Thank you for your comments, I'll fix all this.

Regarding the 200 instead of 304, I did this because the original `Rack::ConditionalGet` is responsible for changing it into a 304. I'll fix this as well.

Regarding the one-liner which puts `Rack::ConditionalGet` at the top of the stack, I got this trick from @rkh a while ago and started to use it quite often for middlewares. I agree it requires a bit of thinking and would not mind changing, although I am not sure what would be the best way. I'll have a look.

Thank you again for the comments.

**Comment by mig-hub** [comment]
@mpalmer, I think I have fixed everything you suggested and tried to make things as clear as possible.

Regarding the one-liner for mounting `Rack::ConditionalGet` I am not sure what is the best way to do it differently. Let me know what you think. In the meantime, I've put a comment in the code to explain this line.

Cheers,
mig

**Comment by mig-hub** [comment]
Sorry CI does not pass because I removed monkey patching from the tests and used `#expect` which does not seem to be accessible in all versions. I thought updating minitest version would resolve this but it doesn't. Worst case scenario I can revert, but I'm quite keen to make this work since the monkey pacthing will be deprecated at some point in minitest.

**Comment by mig-hub** [comment]
Okay I fixed it. I checked the history of minitest in order to see which version introduced `#value`.

**Comment by mig-hub** [comment]
@mpalmer, let me know if everything is fine, if you want me to squash the commits in one, and if you want me to revert commits about monkey patching in tests, since you probably want to do this globally and it exceeds the scope of this pull request.

**Comment by mpalmer** [comment]
Hey @mig-hub, sorry I've been unresponsive.  I've not had an opportunity to re-review your changes in detail, but I'll be going over them in the next day or so; unless there's any egregious problems it'll go into the next release (which should come out on Saturday).

**Comment by mpalmer** [comment]
All your changes look good.  I've merged this, and it'll be in 1.4.0.  Thanks for your contribution to `rack-contrib`!

**Comment by mig-hub** [comment]
Nice thank you.

**Pull request closed without merging**
