### PR TITLE
Ensure JSONP callback is a string when checking if empty.

### LINKED ISSUE #100: Missing value for JSONP callback.
The JSONP middleware will raise a `NoMethodError` when the callback is `nil` from the [`has_callback?`](https://github.com/rack/rack-contrib/blob/c624e1ae4390667e355a7467632b5228716ba551/lib/rack/contrib/jsonp.rb#L67-L69) method. You can recreate it if you provide a `?callback` query string.

I had issues getting the tests running locally, so I'm currently monkey patching it with an added `to_s`:

```ruby
require "rack/contrib/jsonp"

module Rack
  class JSONP
    def has_callback?(request)
      request.params.include?("callback") and not request.params["callback"].to_s.empty?
    end
  end
end
```

### PR DESCRIPTION
**Pull request by tristandunn**
Fixes #100.

### CODE REVIEW

**Comment by mpalmer** [comment]
Looks like a winner.  Thanks!

**Comment by jjb** [comment]
:+1:

**Comment by tristandunn** [comment]
Fixed in a65432d3aaeb624514d9997c77f66f1e8377f159.

**Comment by mpalmer** [comment]
@tristandunn, I was planning on closing the PR when the release had actually been made.

**Comment by tristandunn** [comment]
@mpalmer Ah, figured it was from a rebase. My bad. Want me to restore the repository?

**Comment by mpalmer** [comment]
Nah, it's no problem -- I just usually hold bugs open until they're in a release, so people know what the status is relative to the packages they're likely using.  The release will be in a few days, so I'm sure not too many people will be confused in the meantime.  (grin)

**Pull request closed without merging**
