### PR TITLE
added 'times' to be called in the query string

### PR DESCRIPTION
**Pull request by brycemcd**
Is useful. Solves for Issue #49

### CODE REVIEW

**Comment by mpalmer** [comment]
I'll do the needful on this PR, and get it ready for release.

**Comment by jjb** [comment]
While you're add it, might be nice to have a line of documentation for this feature in the comments.

**Comment by jjb** [comment]
Also: @mperham -- any news thoughts on this since your request (#49) in 2012?

**Comment by mpalmer** [comment]
@jjb hence the needs-docs tag.  (grin)

**Comment by jjb** [comment]
Ah, excellent :)

**Comment by brycemcd** [comment]
@mpalmer looks like interest in this has really picked up. I'm happy to jump back in and resubmit (using your overview on Oct. 31, 2104) and do the doc update if you'd like. Let me know either way. 

The only reason I didn't resubmit before was because I didn't think there was any interest

**Comment by mpalmer** [comment]
@brycemcd, yes rack-contrib was moribund for a while, but a group of us are working to bring it back to life.  If you could put together some docs and tests, that would be *very* helpful, as it would leave me free to put the polish on other PRs.  We're doing monthly feature releases (first-of-the-month or so), so whenever you're able to get it sorted, it'll be released shortly thereafter.

**Comment by brycemcd** [comment]
@mpalmer happy to help out. I have another PR I'm working on at the moment, but I just set aside some time next week to get this taken care of.

**Comment by mpalmer** [comment]
I've created #111 as a cleaned-up version of this PR.  Closing this one.

**Pull request closed without merging**
