### PR TITLE
Filter out HTTP_AUTHORIZATION header contents

### PR DESCRIPTION
**Pull request by mpalmer**
Yeah, e-mailing everyone the base64-encoded credentials for every HTTP basic
auth'd request that generates an error... not cool.  Not cool at *all*.

### CODE REVIEW

**Comment by jjb** [comment]
:+1:

**Comment by jjb** [comment]
Could also filter Digest

**Comment by mpalmer** [comment]
There's no need to filter Digest auth data, because they aren't plaintext (or plaintext-equivalent) absent weaknesses in the crypto -- oh, wait, MD5... (grin).

**Comment by jjb** [comment]
heh, yep. And MD5 weaknesses notwithstanding, the hash can be reused to make any number of subsequent http requests. The attacker can just send the hash, no need to know what the original password is.

**Comment by mpalmer** [comment]
No, that would be "plaintext-equivalent".  Digest prevents replay attacks via the use of a per-request nonce.

**Comment by jjb** [comment]
Huh. I did not know that.

**Comment by jjb** [comment]
The More You Know® :rainbow: :star:

**Pull request closed without merging**
